=== KerwinMa/qtplatz/src/plugins/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- ============================================================================ -->
	<!--
		ModuleType
	-->
	<xs:complexType name="ModuleType" mixed="true">
		<xs:attribute name="name"/>
		<xs:attribute name="type"/>
		<xs:attribute name="filename"/>
	</xs:complexType>
	<!--
		titleType
	-->
	<xs:complexType name="titleType" mixed="true">
		<xs:attribute name="lang">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="en"/>
					<xs:enumeration value="jp"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<!--
		ComponentType
	-->
	<!-- ============================================================================ -->
	<xs:complexType name="ComponentType" mixed="true">
		<xs:attribute name="name" use="optional"/>
		<xs:attribute name="loader" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="adplugin"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="widget"/>
          <xs:enumeration value="dataprovider"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="interface" use="required"/>
		<xs:attribute name="module" use="required"/>
	</xs:complexType>
	<!-- -->
	<!-- ============================================================================ -->
	<xs:complexType name="ServantComponentType" mixed="true">
		<xs:attribute name="name" use="optional"/>
		<xs:attribute name="module" use="required"/>
	</xs:complexType>
	<!-- ============================================================================ -->
	<xs:complexType name="ConfigurationType" mixed="true">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Configuration" type="ConfigurationType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="title" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="pattern" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Component" type="ComponentType" minOccurs="0"/>
			<xs:element name="datasource" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="type"/>
		<xs:attribute name="readonly" type="xs:boolean"/>
	</xs:complexType>
<!-- ============================ Servant ============================================ -->
	<xs:complexType name="ServantConfigurationType" mixed="true">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Configuration" type="ServantConfigurationType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Component" type="ServantComponentType" minOccurs="0"/>
			<xs:element name="datasource" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="type"/>
		<xs:attribute name="readonly" type="xs:boolean"/>
		<xs:attribute name="ns_name"/>
		<xs:attribute name="id"/>
	</xs:complexType>
	<!-- ============================================================================ -->
	<xs:element name="ServantConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Module" type="ModuleType" maxOccurs="unbounded"/>
				<xs:element name="Configuration" type="ServantConfigurationType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- ============================================================================ -->
	<xs:element name="DataprocConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Module" type="ModuleType" maxOccurs="unbounded"/>
				<xs:element name="Configuration" type="ConfigurationType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KerwinMa/qtplatz/src/plugins/dataproc/dataproc.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2010 Toshinobu Hondo, All rights reserved. -->
<!--
   $Id$
-->
<!---<AcquireConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="acquire.config.xsd">
	-->
<DataprocConfiguration name="dataproc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/config.xsd">
	<Module name="qtwidgets" type="sharedlib" filename="/lib/qtPlatz/plugins/ScienceLiaison/qtwidgets$(configuration).dll"/>
	<Configuration name="ProcessMethodEditors">
		<Configuration name="CentroidMethodUI">
      <title>Centroid</title>
			<Component type="widget" interface="qtwidgets::CentroidForm" module="qtwidgets" loader="adplugin"/>
		</Configuration>
		<Configuration name="ElementalCompUI">
      <title>Elemental Comp.</title>
			<Component type="widget" interface="qtwidgets::ElementalCompositionForm" module="qtwidgets" loader="adplugin"/>
		</Configuration>
    <Configuration name="Isotope">
      <title>Isotope</title>
      <Component type="widget" interface="qtwidgets::IsotopeForm" module="qtwidgets" loader="adplugin"/>
    </Configuration>
    <Configuration name="Targeting">
      <title>Targeting</title>
      <Component type="widget" interface="qtwidgets::TargetingForm" module="qtwidgets" loader="adplugin"/>
    </Configuration>

    <Configuration name="MSCalibrationUI">
      <title>MS Calibration</title>
			<Component type="widget" interface="qtwidgets::MSCalibrationForm" module="qtwidgets" loader="adplugin"/>
		</Configuration>
		<Configuration name="MSLockMassUI">
      <title>Lock Mass</title>
			<Component type="widget" interface="qtwidgets::MSLockForm" module="qtwidgets" loader="adplugin"/>
		</Configuration>
    <Configuration name="PeakMethodUI">
      <title>Chromatogram Peak Method</title>
      <Component type="widget" interface="qtwidgets::PeakMethodForm" module="qtwidgets" loader="adplugin"/>
    </Configuration>
    <Configuration name="PeakIDTableUI">
      <title>Chromatogram ID Table</title>
      <Component type="widget" interface="qtwidgets::PeakIDTableForm" module="qtwidgets" loader="adplugin"/>
    </Configuration>
    <Configuration name="ReportUI">
      <title>Report</title>
      <Component type="widget" interface="qtwidgets::ReportForm" module="qtwidgets" loader="adplugin"/>
    </Configuration>
    <Configuration name="Memo">
      <title>Memo Pad</title>
      <Component type="widget" interface="qtwidgets::EditForm" module="qtwidgets" loader="adplugin"/>
    </Configuration>
  </Configuration>
</DataprocConfiguration>
